# Generated by Django 3.2.9 on 2023-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(default=0000, max_length=15),
            preserve_default=False,
        ),
    ]
