# Generated by Django 3.2.9 on 2023-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_location_distanations'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='shipment_cost',
            field=models.FloatField(default=0),
        ),
    ]
