# Generated by Django 3.2.9 on 2023-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
