# Generated by Django 3.2.9 on 2023-06-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230609_2217'),
        ('product', '0002_category_photo'),
    ]

    operations = [
    ]
