# Generated by Django 3.2.9 on 2023-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_0002_auto_20230609_2217_0002_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_locations',
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
