# Generated by Django 3.2.9 on 2023-06-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20230618_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='many',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
