# Generated by Django 3.2.9 on 2023-11-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_children'),
        ('product', '0008_product_many'),
        ('product', '0011_basket'),
    ]

    operations = [
    ]
