# Generated by Django 3.2.9 on 2023-11-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20231112_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='children',
        ),
        migrations.RemoveField(
            model_name='product',
            name='many',
        ),
    ]
