(
    HOME, CHOOSE, MENU, MY_ORDERS, ADDRESSES_LIST, 
    CATEGORY_LIST, TYPE_OF_LIST, CHOOSE_BIG_OR_MINI, COUNT_OF_PRODUCT, TEST,
    WRITE_COMMENT, COMMENT_DONE,
    GET_LANGUAGE, HAVE_DONE,
    LOCATION_CONFIRM,
) = range(15)